include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = RecordPauseiOS8
RecordPauseiOS8_FILES = Tweak.xm
RecordPauseiOS8_FRAMEWORKS = CoreGraphics UIKit
RecordPauseiOS8_LIBRARIES = substrate
RecordPauseiOS8_INSTALL_PATH = /Library/Application Support/RecordPause

include $(THEOS_MAKE_PATH)/library.mk
